Cleanup copysshkey. Also, now errors if the host is unavailable.

diff --git a/bin/copysshkey b/bin/copysshkey
--- a/bin/copysshkey
+++ b/bin/copysshkey
@@ -1,23 +1,27 @@
 #!/bin/sh
 # source: http://hints.macworld.com/article.php?story=2007091814022049
 
+set -e
+
 KEY="$HOME/.ssh/id_dsa.pub"
 
-if [ ! -f ~/.ssh/id_dsa.pub ];then
-    echo "private key not found at $KEY"
-    echo "* please create it with "ssh-keygen -t dsa" *"
-    echo "* to login to the remote host without a password, don't give the key you create with ssh-keygen a password! *"
+if [ ! -f $KEY ];then
+    echo "Private key not found at $KEY. Please create it by issuing the following command:"
+    echo
+    echo "    ssh-keygen -t dsa"
+    echo
+    echo "To enable passwordless login on the remote host, don't give this key a password."
     exit
 fi
 
 if [ -z $1 ];then
-    echo "Please specify user@host as the first switch to this script"
+    echo "Usage: copysshkey user@host"
     exit
 fi
 
 echo "Putting your key on $1... "
 
 KEYCODE=`cat $KEY`
-ssh -q $1 "mkdir ~/.ssh 2>/dev/null; chmod 700 ~/.ssh; echo "$KEYCODE" >> ~/.ssh/authorized_keys; chmod 644 ~/.ssh/authorized_keys"
+ssh $1 "mkdir ~/.ssh 2>/dev/null; chmod 700 ~/.ssh; echo "$KEYCODE" >> ~/.ssh/authorized_keys; chmod 644 ~/.ssh/authorized_keys; exit"
 
 echo "Done!"
